### ISSUE TITLE
no longer produces links for active EC2's

### ISSUE THREAD

**Issue by ponchoh** [alexvea/start-stop-AWS-instances-powershell#2]
Running `check_aws_instances.ps1` doesn't create a link for active instances, like bellow:

![image](https://github.com/alexvea/start-stop-AWS-instances-powershell/assets/85764737/959e1bc2-dbad-4e9c-9248-68d1c31183b7)

**Comment by ponchoh** [comment]
sorry, running the script again worked but I am missing some, found out it only targets "stop-only" thanks

💯

**Comment by alexvea** [comment]
Hello Hector, yes it's filtering tag Name and tag Schedule with value 'stop-only' to avoid accidently stop CC shared instance with your tag Name.
